SignerServerURL = "--- Signer Server URL ---"
OperatorAddress = "--- Operator Address ---"
OperatorKeyAccountID = "--- Operator Key Account ID ---"
SignerKeyAccountID = "--- Signer Key Account ID ---"
EthereumRPCURL = "--- Ethereum RPC URL (mainnet / holesky) ---"
L1RPCEndpoint = "--- L1 RPC Endpoint (mainnet) ---"
BeaconURL = "--- Beacon Endpoint (mainnet) ---"
BLSCurve = "BN254"

[[Chains]]
ChainName = "optimism"
L2RPCEndpoint = "--- L2 RPC Endpoint optimism ---"
NumberOfAttestationNodes = 1

[[Chains.AttestationNodes]]
BLSKeyAccountID = "--- BLS Key Account ID ---"
ConcurrentFetchers = 8
MetricsEnabled = true
MetricsServerPort = "8080"
HostBindingPort = "8080"
MetricsServiceName = "lagrange-node"
PrometheusRetentionTime = "60s"

[[Chains]]
ChainName = "base"
L2RPCEndpoint = "--- L2 RPC Endpoint base ---"
NumberOfAttestationNodes = 1

[[Chains.AttestationNodes]]
BLSKeyAccountID = "--- BLS Key Account ID ---"
ConcurrentFetchers = 8
MetricsEnabled = true
MetricsServerPort = "8080"
HostBindingPort = "8081"
MetricsServiceName = "lagrange-node"
PrometheusRetentionTime = "60s"

[[Chains]]
ChainName = "arbitrum"
L2RPCEndpoint = "--- L2 RPC Endpoint arbitrum ---"
NumberOfAttestationNodes = 1

[[Chains.AttestationNodes]]
BLSKeyAccountID = "--- BLS Key Account ID ---"
ConcurrentFetchers = 8
MetricsEnabled = true
MetricsServerPort = "8080"
HostBindingPort = "8082"
MetricsServiceName = "lagrange-node"
PrometheusRetentionTime = "60s"