{
 "title": "Lagrange Optimism Metrics",
 "description": "1 being the highest.\n\n0 - you are not opted in that quorum",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Batch Number - Committed Batch Number",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(client_current_batch_number{service=\"lagrange-node\", module=\"client_optimism\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(client_commit_batch_number{service=\"lagrange-node\", module=\"client_optimism\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time [ms] to get the current batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "client_get_batch_request{service=\"lagrange-node\", module=\"client_optimism\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time [ms] to fetch L2 block hashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rpc_fetch_l2_block_hashes{service=\"lagrange-node\", module=\"client_optimism\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time [ms] to fetch L1 blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rpc_fetch_l1_blocks{service=\"lagrange-node\", module=\"client_optimism\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time [ms] to fetch beacon blobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rpc_fetch_beacon_blobs{service=\"lagrange-node\", module=\"client_optimism\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}